name: Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.x'
    - name: Prepare pulling cmake installed libraries
      run: |
        mkdir -p $HOME/cmake
        echo "CMAKE_INSTALL_PREFIX=$HOME/cmake" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with: 
        name: gklib-linux-gcc
        repo: worc4021/GKlib
        path: $HOME/cmake
        workflow: ci.yml
    - name: Configure
      run: |
        cmake --preset linux-gcc-release-config
      working-directory: ${{ github.workspace }}
    - name: Build
      run: |
        cmake --build --preset linux-gcc-release-build --target install
      working-directory: ${{ github.workspace }}
    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: gklib-linux-gcc
        path: ${{ github.workspace }}/out/install/linux-gcc-release-config
 

#   windows-build:
#     runs-on: windows-latest
#     defaults:
#       run:
#         shell: bash
#     steps:
#     - uses: actions/checkout@v3
#     - name: Setup Ninja
#       uses: seanmiddleditch/gha-setup-ninja@master
#     - name: Setup cmake
#       uses: jwlawson/actions-setup-cmake@v2
#       with:
#         cmake-version: '3.29.x'
#     - uses: worc4021/oneApi@v1
#     - name: Configure
#       run: |
#         cmake --preset windows-intel-release-config
#       working-directory: ${{ github.workspace }}
#       shell: cmd
#     - name: Build
#       run: |
#         cmake --build --preset windows-intel-release-build --target install
#       working-directory: ${{ github.workspace }}
#       shell: cmd
#     - name: Upload library
#       uses: actions/upload-artifact@v4
#       with:
#         name: gklib-windows-intel
#         path: ${{ github.workspace }}/out/install/windows-intel-release-config