name: Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
  workflow_dispatch:

jobs:
  linux-build:
    strategy:
      matrix:
        compiler: 
        - gcc
        - intel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: worc4021/oneApi@v7
      if: ${{ matrix.compiler == 'intel' }}
      with:
        icx: true
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.x'
    - name: Prepare pulling cmake installed libraries
      run: |
        echo "CMAKE_INSTALL_PREFIX=${{ runner.TEMP }}" >> $GITHUB_ENV
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with: 
        name: gklib-linux-${{ matrix.compiler }}
        repo: worc4021/GKlib
        path: ${{ runner.TEMP }}
        workflow: ci.yml
    - name: Configure
      run: |
        cmake --preset linux-${{ matrix.compiler }}-release-config
      working-directory: ${{ github.workspace }}
    - name: Build
      run: |
        cmake --build --preset linux-${{ matrix.compiler }}-release-build --target install
      working-directory: ${{ github.workspace }}
    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: metis-linux-${{ matrix.compiler }}
        path: ${{ github.workspace }}/out/install/linux-${{ matrix.compiler }}-release-config
 

  windows-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: worc4021/oneApi@v7
      with:
        icx: true
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.x'
    - name: Prepare pulling cmake installed libraries
      run: |
        echo "CMAKE_INSTALL_PREFIX=${{ runner.TEMP }}" >> $GITHUB_ENV
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with: 
        name: gklib-windows-intel
        repo: worc4021/GKlib
        path: ${{ runner.TEMP }}
        workflow: ci.yml
    
    - name: Configure
      run: |
        cmake --preset windows-intel-release-config
      working-directory: ${{ github.workspace }}
      shell: cmd
    - name: Build
      run: |
        cmake --build --preset windows-intel-release-build --target install
      working-directory: ${{ github.workspace }}
      shell: cmd
    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: metis-windows-intel
        path: ${{ github.workspace }}/out/install/windows-intel-release-config